### ISSUE TITLE
Ask for help when running the project!!!

### ISSUE THREAD

**Issue by lamcrazy** [fletcher/c-sss#9]
Hi all,

having a problem when running the project in vs2019, in  shamir.c (137,12): error C2466: cannot allocate an array of constant size 0
Before this step, I have generated the cmake project to fit in vs2019 using cmake gui tools
OS: win10
IDE: Visual Studio 2019

	int * split_number(int number, int n, int t) {
        int * shares = malloc(sizeof(int) * n);
	int coef[t];
	int x;
	int i;
by the way,what steps should I follow to run the code normally after downloading the project？can you give me some suggestions? Thank you!!!!!!

**Comment by fletcher** [comment]
Pushed a new version that should fix this.

To run the program, follow the directions in the README or the  documentation (linked to from the bottom of the README or the repo information in this github repository.)

**Comment by lamcrazy** [comment]
Hi all,
I'm sorry that the errors are still existing.
I downloaded the latest version, and used the cmake-gui tool to generate the vs project,but when debuging the project in vs2019, it still display the errrors.

So I guess maybe my steps or my tools could not fit the source code. At the same time, I could not find the directions in the README（except for the "About the Source"） about choosing which tools to run the program and the documentation link is banned. Could you share your tools(softwear) and your steps in deatils about running the source code? Thanks a lot!!!!!!!

![pic1](https://user-images.githubusercontent.com/47603246/88908320-49955800-d28c-11ea-9a83-d74de89bf079.png)
![pic2](https://user-images.githubusercontent.com/47603246/88908336-5023cf80-d28c-11ea-8a98-59c0c18cdb89.png)
